name: Update Api

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  pushContainer:
    runs-on: self-hosted

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Golang
        id: setup_golang
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true
          cache: false

      - name: install make
        run: sudo apt update; sudo apt-get install wget build-essential -y
      - name: Update & regenerate
        run: make gen
      - name: Make sure testbuild still works.
        run: make gen

      - name: Commit & Push changes
        id: commit_all_inputs
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Automated OpenApi YAML Update"
          branch: "main"

      - name: Bump Version Tag.
        id: bump_tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor
          DRY_RUN: false
          VERBOSE: true
          GIT_API_TAGGING: false
